### ISSUE TITLE
SectorFile not saving entity

### ISSUE THREAD

**Issue by 404Setup** [LevelTranic/Vine#10]
### Expected behavior

After shutting down the server, the new entity is saved

### Observed/Actual behavior

After restarting the server, the entity is lost

### Steps/models to reproduce

1. Switch region format to SECTORFILE
2. Start the server and generate some entities
3. Shut down the server to save the map
4. Restart the server, those entities are lost

### Plugin and Datapack List

It's not their problem

### Configuration files

Vine.yml
```yaml
# Vine Abstract Configuration
# Vine Github: https://github.com/LevelTranic/Vine
# It is recommended to always keep the latest version, download it at https://tranic.one/downloads/vine

feature:
  # If the player is blocked on the top of the player's head, he will not try to rebirth 
  # the player on the ceiling.
  # This is suitable for those servers with ceilings.
  disable-respawn-ceiling: true
  # Try virtual threads. Once enabled, all explicit platform threads will 
  # be replaced with virtual threads as much as possible, which may have 
  # some adverse consequences. Please enable it with caution.
  try-virtual-threads: true
  vanilla-hopper: false
  # Changes the seed from 64bit to 1024bit, this will strictly secure your seed,
  # making it almost impossible to crack.
  # Warning: You must delete existing maps to switch the state of the secure seed,
  # and do not modify it during hot loading, otherwise the server will crash and
  # cannot continue to load maps.
  secure-seed: false
  # Change all triangle distribution in Minecraft randomizers into uniform distribution
  # With that edge cases are more likely to happen
  flatten-triangular-distribution: false
  disable-spark: false
  zero-tick-plants: true
  dont-save-entity:
    # Disable save primed tnt on chunk unloads.
    # Useful for redstone server, can prevent machine be exploded by TNT,
    # when player disconnected caused by Internet issue.
    primed-tnt: true
    falling-block: true
  cache-player-profile-result:
    # Cache the player profile result on they first join.
    # It's useful if Mojang's verification server is down.
    enabled: true
    # The timeout of the cache. Unit: Minutes.
    timeout: 1440
  region:
    # Region Format: ANVIL (Default), LINEAR, SECTORFILE
    # LINEAR: https://github.com/xymb-endcrystalme/LinearRegionFileFormatTools
    # SECTORFILE: https://github.com/PaperMC/SectorTool/blob/master/SPECIFICATION.MD
    # If you are not worried about disk capacity, please do not use Linear, it is still
    # experimental and may cause data corruption.
    format: SECTORFILE
    # Only applicable to SECTORFILE, support list:
    # "GZIP, ZLIB, NONE, LZ4, BROTLI, SNAPPY, ZSTD"
    # Brotli is only available on TranicServer for Vine.
    # There is currently no tool to convert it back to ANVIL. Enable with caution!
    compression-format: ZSTD
    # Only applicable to Linear, this is the compression level provided by ZSTD.
    # The available range is 1-22. When the compression level exceeds 14, 
    # the CPU pressure, chunk refresh time and memory usage will increase significantly, 
    # and high compression levels have the risk of losing chunk data, 
    # so we will limit it to the range of 1-15 to avoid some simple problems.
    compression-level: 1
    # Only applicable to Linear, chunk refresh interval, default is 5 (seconds)
    flush-frequency: 5
fix:
  villagers-dont-release-memory: true
  # Ensures correct destinations when travelling back and forth through Nether Portals in Multiplayer.
  nether-portal: true
  # Fixes some entities not bouncing on slime blocks and getting stuck
  # Fixes: https://bugs.mojang.com/browse/MC-216985
  incorrect-bounce-logic: true
  # Fixes Explosions being able to destroy item frames in water
  # Fixes: https://bugs.mojang.com/browse/MC-3697
  explosion-breaks-item-frame-in-water: true
  anvil-drop:
    # This fix will attempt to prevent the bug in https://github.com/PaperMC/Folia/issues/217, 
    # it may cause some unexpected effects but should be harmless.
    enabled: true
    # Whether to print detailed information to the console when this issue is triggered
    debug: false
optimize:
  # Reduce acquire POI for stuck entities
  acquire-poi-for-stuck-entity: 60
  # May cause the inconsistent order of future compose tasks.
  faster-structure-gen-future-sequencing: false
  floating-point-positive: false
  # If true, disables the frequent pathfinds done while already following a path
  mob-re-pathfinding: true
  noise-generation: true
  # Whether to skip some raid checks.
  # Enabling this will significantly reduce the server's performance.
  skip-self-raid-check: false
  load-chunks:
    spawn-phantoms: true
    activate-climbing-entities: true
  zombie-search-and-destroy-turtle-egg:
    # If true, optimizes the expensive searching done to find a turtle egg to crush, for zombies/husks, by default fully disabling it
    enabled: false
    # Percent chance to run for task: zombie seeking turtle eggs to destroy
    percent-chance: 40
  minecart:
    # Enable this feature to handle large amount of stacked Minecart better.
    # By skipping tick collisions to reduce expense getting entities list
    # and bukkit event calls, useful for the anarchy server.
    enabled: true
    skipTickCount: 30
```

### Vine version

Vine September Test 1.20.6-DEV-237f0fb
